services:
  - name: ask-richter-backend
    type: web
    env: node
    plan: free
    buildCommand: "npm install && npx turbo run build --filter=backend"
    # --- MUDANÇA CRÍTICA AQUI ---
    # Primeiro, roda o script de download usando tsx.
    # Se for bem-sucedido (&&), então inicia o servidor principal.
    startCommand: "npx tsx apps/backend/src/scripts/download-index.ts && node apps/backend/dist/index.js"
    healthCheckPath: /api/health
    envVars:
      - fromGroup: ask-richter-secrets
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - "apps/backend/**"
        - "packages/**"
