services:
  # Serviço para o nosso backend Node.js
  - name: ask-richter-backend
    type: web
    env: node
    plan: free
    rootDir: apps/backend
    buildCommand: "npm install && npx tsc"
    startCommand: "node dist/index.js"
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: AI_PROVIDER
        value: huggingface # Lembre-se de mudar para 'huggingface' em produção se desejar
      - fromGroup: ask-richter-secrets # Apenas referenciamos o nome do grupo
    buildFilter:
      paths:
        - "apps/backend/**"
        - "packages/**"
