# Define os grupos de variáveis de ambiente primeiro
envVarGroups:
  - name: ask-richter-secrets
    envVars:
      - key: OPENAI_API_KEY
      - key: SUPABASE_URL
      - key: SUPABASE_SERVICE_ROLE_KEY
      - key: SUPABASE_BUCKET_NAME
      - key: HUGGINGFACE_API_KEY

services:
  # Serviço para o nosso backend Node.js
  - name: ask-richter-backend
    type: web
    env: node
    plan: free
    rootDir: apps/backend
    buildCommand: "npm install && npx tsc"
    startCommand: "node dist/index.js"
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: AI_PROVIDER
        value: huggingface # Lembre-se de mudar para 'huggingface' em produção se desejar
      - fromGroup: ask-richter-secrets # Referencia o grupo de segredos definido acima
    buildFilter:
      paths:
        - "apps/backend/**"
        - "packages/**"
