services:
  - name: ask-richter-backend
    type: web
    env: node
    plan: free
    # rootDir não é mais necessário aqui, pois o turbo gerencia os caminhos
    buildCommand: "npm install && npx turbo run build --filter=backend"
    startCommand: "node apps/backend/dist/index.js" # Caminho completo para o arquivo de início
    healthCheckPath: /api/health
    envVars:
      - fromGroup: ask-richter-secrets
      # Outras variáveis públicas podem ser adicionadas aqui
      # - key: AI_PROVIDER
      #   value: huggingface
    buildFilter:
      paths:
        - "apps/backend/**"
        - "packages/**"
